force-app/RecordActions/default/objects/sflib_RecordAction__c/sflib_RecordAction__c.object-meta.xml
<CustomObject>
    <description>Holds the record actions, offered by the SFLib Record Action feature</description>
    <label>Record Action</label>
    <nameField>
        <label>Record Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/FlowName__c.field-meta.xml
<CustomField>
    <fullName>FlowName__c</fullName>
    <description>The API name of the screen flow which will be run when the call-to-action button is clicked</description>
    <inlineHelpText>The API name of the screen flow</inlineHelpText>
    <label>Screen Flow Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <defaultValue>&quot;1&quot;</defaultValue>
    <inlineHelpText>e.g. &quot;1 AND 2 OR 3&quot;</inlineHelpText>
    <label>Formula</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <inlineHelpText>The name of the Icon to show, leave this blank if you do not want to have an icon</inlineHelpText>
    <label>Icon</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>10</defaultValue>
    <inlineHelpText>The actions will show in ascending order</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <description>The API name of the record SObjectType for which this action should be available</description>
    <inlineHelpText>The API name of the object for which this action should be available</inlineHelpText>
    <label>Object Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/sflib_RecordActionCondition__c.object-meta.xml
<CustomObject>
    <label>Record Action Condition</label>
    <nameField>
        <displayFormat>RAC{0000000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Action Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <label>Formula</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/fields/RecordAction__c.field-meta.xml
<CustomField>
    <fullName>RecordAction__c</fullName>
    <label>Record Action</label>
    <referenceTo>sflib_RecordAction__c</referenceTo>
    <relationshipLabel>Record Action Conditions</relationshipLabel>
    <relationshipName>RecordActionConditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>Object Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/RecordActions/default/classes/selectors/sflib_RecordActionsSelector.cls
/**
 * sflib_RecordActionsSelector class
 *
 * Selector Class providing common database query support for abstracting and encapsulating query logic
 */
public virtual without sharing class sflib_RecordActionsSelector
		extends fflib_SObjectSelector
		implements sflib_IRecordActionsSelector
{
	/**
	 * The current implementation type of the service
	 */
	private static System.Type implementationType = sflib_RecordActionsSelector.class;

	/**
	 * The implementation replacement for the service,
	 */
	private static sflib_IRecordActionsSelector implementationReplacement;

	/**
	 * Runs the query in User Mode, respecting FLS, CRUD & sharing rules
	 *
	 * @return New instance of the selector
	 */
	public static sflib_IRecordActionsSelector newInstance()
	{
		sflib_IRecordActionsSelector selector =
				(implementationReplacement == null) ? (sflib_IRecordActionsSelector) implementationType.newInstance() : implementationReplacement;
		selector.setDataAccess(fflib_SObjectSelector.DataAccess.USER_MODE);
		return selector;
	}

	/**
	 * Runs the query in System Mode, disabling FLS, CRUD & sharing rules
	 *
	 * @return New instance of the selector
	 */
	public static sflib_IRecordActionsSelector newElevatedInstance()
	{
		sflib_IRecordActionsSelector selector =
				(implementationReplacement == null) ? (sflib_IRecordActionsSelector) implementationType.newInstance() : implementationReplacement;
		selector.setDataAccess(fflib_SObjectSelector.DataAccess.SYSTEM_MODE);
		return selector;
	}

	/**
	 * Class constructor
	 * This should not be used directly by an application but only by fflib
	 */
	public sflib_RecordActionsSelector()
	{
		super();
	}

	/**
	 * The fields to always include in all queries
	 *
	 * @return Returns a list of default fields that are always queried
	 */
	public virtual List<Schema.SObjectField> getSObjectFieldList()
	{
		List<SObjectField> result = new List<Schema.SObjectField>
		{
				sflib_RecordAction__c.Id,
				sflib_RecordAction__c.Description__c,
				sflib_RecordAction__c.FlowName__c,
				sflib_RecordAction__c.Formula__c,
				sflib_RecordAction__c.Icon__c,
				sflib_RecordAction__c.Order__c,
				sflib_RecordAction__c.SObjectType__c,
				sflib_RecordAction__c.Status__c
		};
		// Uncomment the line below if the selector is extend from another selector,
		// result.addAll(super.getSObjectFieldList());
		return result;
	}

	/**
	 * Defines the SObjectType for this selector
	 *
	 * @return the SObjectType of this selector
	 */
	public Schema.SObjectType getSObjectType()
	{
		return Schema.sflib_RecordAction__c.SObjectType;
	}

	/**
	 * Replace the default implementation of the service
	 *
	 * @param systemType The System.Type of the replacement class
	 */
	public static void replaceWith(System.Type systemType)
	{
		sflib_RecordActionsSelector.implementationType = systemType;
	}

	/**
	 * Replace the default implementation of the service
	 *
	 * @param replacement A replacement instance
	 *
	 * @see sflib_IRecordActionsSelector
	 */
	public static void replaceWith(sflib_IRecordActionsSelector replacement)
	{
		sflib_RecordActionsSelector.implementationReplacement = replacement;
	}

	/**
	 * Queries sflib_RecordAction__c records by their record Id
	 *
	 * @param idSet A set of `sflib_RecordAction__c.Id` values
	 *
	 * @return A list of `sflib_RecordAction__c` records
	 */
	public virtual List<sflib_RecordAction__c> selectById(Set<Id> idSet)
	{
		return Database.query(
				newQueryFactory()
						.setCondition('Id IN :idSet')
						.toSOQL()
		);
	}

	/**
	 * Queries sflib_RecordAction__c records by their SObjectType value
	 *
	 * @param sObjectTypeNames A set of `sflib_RecordAction__c.SObjectType__c` values
	 *
	 * @return A list of `sflib_RecordAction__c` records
	 */
	public List<sflib_RecordAction__c> selectBySObjectType(Set<String> sObjectTypeNames) {
		fflib_QueryFactory queryFactory = newQueryFactory();

		((fflib_SObjectSelector) sflib_RecordActionConditionsSelector.newInstance())
				.addQueryFactorySubselect(
						queryFactory,
						'RecordActionConditions__r'
				);

		return Database.query(
				queryFactory
						.setCondition('SObjectType__c IN :sObjectTypeNames')
						.toSOQL()
		);
	}

	public override String getOrderBy() {
		return 'Order__c ASC';
	}
}