force-app/RecordActions/default/objects/sflib_RecordAction__c/sflib_RecordAction__c.object-meta.xml
<CustomObject>
    <description>Holds the record actions, offered by the SFLib Record Action feature</description>
    <label>Record Action</label>
    <nameField>
        <label>Record Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionHistory__c/sflib_RecordActionHistory__c.object-meta.xml
<CustomObject>
    <label>Record Action History</label>
    <nameField>
        <displayFormat>A{0000000000}</displayFormat>
        <label>Record Action History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Action History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/RecordActions/default/objects/sflib_RecordActionHistory__c/fields/RecordAction__c.field-meta.xml
<CustomField>
    <fullName>RecordAction__c</fullName>
    <label>Record Action</label>
    <referenceTo>sflib_RecordAction__c</referenceTo>
    <relationshipLabel>Record Action History</relationshipLabel>
    <relationshipName>RecordActionHistory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionHistory__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>The ID of the record for which the action was executed</description>
    <label>Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionHistory__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/RecordActions/default/classes/controllers/sflib_RecordActionHistoryController.cls
/**
 * sflib_RecordActionHistoryController
 *
 * Controller for the LWC sflibRecordActionHistory and for generic history functions
 *
  * @author architect ir. Wilhelmus G.J. Velzeboer
 *
 * Copyright (c), W.G.J. Velzeboer,
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above author notice,
 *      this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 * - Neither the name of the author nor the names of its contributors
 *      may be used to endorse or promote products derived from this software without
 *      specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @see sflibRecordActionHistory
 * @see sflibRecordAction
 */
public with sharing class sflib_RecordActionHistoryController {

    /**
     * Gets a list of record action history
     *
     * @param recordIdString The record Id for which to get the history
     *
     * @return Returns a list of sflib_RecordActionHistory DTOs
     *
     * @see sflib_RecordActionHistoryController.sflib_RecordActionHistory
     */
    @AuraEnabled(Cacheable=true)
    public static List<sflib_RecordActionHistory> getHistory(String recordIdString) {
        try {
            Id recordId = Id.valueOf(recordIdString);

            List<sflib_RecordActionHistory> result = new List<sflib_RecordActionHistory>();
            for (sflib_RecordActionHistory__c record :
                    sflib_RecordActionHistorySelector.newInstance()
                            .selectByRecordId(new Set<Id>{
                                    recordId
                            })) {
                result.add(new sflib_RecordActionHistory(record));
            }
            return result;
        } catch (Exception e) {
            AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
            auraHandledException.setMessage(e.getMessage());
            throw auraHandledException;
        }
    }

    /**
     * Gets a list of record action history
     *
     * @param actionLogId The `sflib_RecordActionHistory__c.Id` value when updating a history record, use null for new records
     * @param recordId The record Id for which to get the history
     * @param actionId The `sflib_RecordAction__c.Id` value of the action to log
     * @param status The (new) status value to store
     *
     * @return Returns a list of sflib_RecordActionHistory DTOs
     *
     * @see sflib_RecordActionHistoryController.sflib_RecordActionHistory
     */
    @AuraEnabled(Cacheable=false)
    public static String logAction(String actionLogId, String recordId, String actionId, String status) {
        try {
            sflib_RecordActionHistory__c record = new sflib_RecordActionHistory__c(
                    Id = String.isNotBlank(actionLogId) ? Id.valueOf(actionLogId) : null,
                    RecordId__c = Id.valueOf(recordId),
                    RecordAction__c = Id.valueOf(actionId),
                    Status__c = status
            );
            upsert record;
            return record.Id;
        } catch (Exception e) {
            AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
            auraHandledException.setMessage(e.getMessage());
            throw auraHandledException;
        }
    }

    /**
     * Data Transfer Object with the History details
     */
    public class sflib_RecordActionHistory {

        /**
         * The `sflib_RecordAction__c.Id` value that was executed
         */
        @AuraEnabled public Id actionId { get; set; }

        /**
         * The `sflib_RecordAction__c.Name` value
         */
        @AuraEnabled public String actionName { get; set; }

        /**
         * The `User.Id` value of the user that created the history log item
         */
        @AuraEnabled public Id createdById { get; set; }

        /**
         * The created date of the history log item
         */
        @AuraEnabled public Datetime createdDate { get; set; }

        /**
         * The `sflib_RecordActionHistory__c.Id` value
         */
        @AuraEnabled public Id id { get; set; }

        /**
         * The `sflib_RecordActionHistory__c.RecordId__c` value of the record used by the record action
         */
        @AuraEnabled public String recordId { get; set; }

        /**
         * The `sflib_RecordAction__c.Status__c` value
         */
        @AuraEnabled public String status { get; set; }

        /**
         * The name of the the user that created the history log item
         */
        @AuraEnabled public String userName { get; set; }


        /**
         * DTO class constructor
         * @param record The sflib_RecordActionHistory__c used for constructing the DTO
         */
        public sflib_RecordActionHistory(sflib_RecordActionHistory__c record) {
            Security.stripInaccessible(
                    AccessType.READABLE,
                    new List<sflib_RecordActionHistory__c>{ record }
            );
            this.actionId = record.RecordAction__c;
            this.actionName = record.RecordAction__r.Name;
            this.createdById = record.CreatedById;
            this.createdDate = record.CreatedDate;
            this.id = record.Id;
            this.recordId = record.RecordId__c;
            this.status = record.Status__c;
            this.userName = record.CreatedBy.Name;
        }
    }
}