force-app/RecordActions/default/objects/sflib_RecordAction__c/sflib_RecordAction__c.object-meta.xml
<CustomObject>
    <description>Holds the record actions, offered by the SFLib Record Action feature</description>
    <label>Record Action</label>
    <nameField>
        <label>Record Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <description>The API name of the record SObjectType for which this action should be available</description>
    <inlineHelpText>The API name of the object for which this action should be available</inlineHelpText>
    <label>Object Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/sflib_RecordActionCondition__c.object-meta.xml
<CustomObject>
    <label>Record Action Condition</label>
    <nameField>
        <displayFormat>RAC{0000000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Action Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/fields/RecordAction__c.field-meta.xml
<CustomField>
    <fullName>RecordAction__c</fullName>
    <label>Record Action</label>
    <referenceTo>sflib_RecordAction__c</referenceTo>
    <relationshipLabel>Record Action Conditions</relationshipLabel>
    <relationshipName>RecordActionConditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>Object Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/RecordActions/tests/apex/classes/recordActions/triggerActions/sflib_RecordActionConditionTATest.cls
/**
 * sflib_RecordActionConditionTATest class
 *
 * Unit test class for the sflib_RecordActionConditionTriggerAction class
 *
  * @author architect ir. Wilhelmus G.J. Velzeboer
 *
 * Copyright (c), W.G.J. Velzeboer,
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above author notice,
 *      this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 * - Neither the name of the author nor the names of its contributors
 *      may be used to endorse or promote products derived from this software without
 *      specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @see sflib_RecordActionConditionTriggerAction
 */
@IsTest
private class sflib_RecordActionConditionTATest {

    @IsTest
    static void itShouldValidate() {

        final Id recordActionId = fflib_IDGenerator.generate(sflib_RecordAction__c.SObjectType);
        sflib_RecordActionCondition__c recordA = generateRecordActionCondition(recordActionId, 1);
        sflib_RecordActionCondition__c recordB = generateRecordActionCondition(recordActionId, 2);
        List<sflib_RecordActionCondition__c> records = new List<sflib_RecordActionCondition__c>{recordA, recordB};

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        sflib_IRecordActionsService serviceMock = (sflib_IRecordActionsService) mocks.mock(sflib_IRecordActionsService.class);

        sflib_RecordActionsService.replaceWith(serviceMock);

        fflib_TriggerContext triggerContext = new fflib_TriggerContext(records);
        triggerContext.triggerOperation = TriggerOperation.AFTER_INSERT;
        sflib_RecordActionConditionTriggerAction triggerAction = new sflib_RecordActionConditionTriggerAction();
        triggerAction.setContext(triggerContext);

        System.Test.startTest();
        triggerAction.doWork();
        triggerContext.triggerOperation = TriggerOperation.AFTER_UPDATE;
        triggerAction.doWork();
        triggerContext.triggerOperation = TriggerOperation.AFTER_DELETE;
        triggerAction.doWork();
        triggerContext.triggerOperation = TriggerOperation.AFTER_UNDELETE;
        triggerAction.doWork();
        System.Test.stopTest();

        ((sflib_IRecordActionsService) mocks.verify(serviceMock, 4)).validate(records);
    }

    private static sflib_RecordActionCondition__c generateRecordActionCondition(Id recordActionId, Decimal conditionNumber) {
        return new sflib_RecordActionCondition__c(
                Id = fflib_IDGenerator.generate(sflib_RecordActionCondition__c.SObjectType),
                SObjectType__c = 'Account',
                RecordAction__c = recordActionId,
                Number__c = conditionNumber
        );
    }
}