force-app/RecordActions/default/objects/sflib_RecordAction__c/sflib_RecordAction__c.object-meta.xml
<CustomObject>
    <description>Holds the record actions, offered by the SFLib Record Action feature</description>
    <label>Record Action</label>
    <nameField>
        <label>Record Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/FlowName__c.field-meta.xml
<CustomField>
    <fullName>FlowName__c</fullName>
    <description>The API name of the screen flow which will be run when the call-to-action button is clicked</description>
    <inlineHelpText>The API name of the screen flow</inlineHelpText>
    <label>Screen Flow Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <defaultValue>&quot;1&quot;</defaultValue>
    <inlineHelpText>e.g. &quot;1 AND 2 OR 3&quot;</inlineHelpText>
    <label>Formula</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>10</defaultValue>
    <inlineHelpText>The actions will show in ascending order</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <description>The API name of the record SObjectType for which this action should be available</description>
    <inlineHelpText>The API name of the object for which this action should be available</inlineHelpText>
    <label>Object Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordAction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Draft&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/sflib_RecordActionCondition__c.object-meta.xml
<CustomObject>
    <label>Record Action Condition</label>
    <nameField>
        <displayFormat>RAC{0000000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Action Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <label>Formula</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/fields/RecordAction__c.field-meta.xml
<CustomField>
    <fullName>RecordAction__c</fullName>
    <label>Record Action</label>
    <referenceTo>sflib_RecordAction__c</referenceTo>
    <relationshipLabel>Record Action Conditions</relationshipLabel>
    <relationshipName>RecordActionConditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/RecordActions/default/objects/sflib_RecordActionCondition__c/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>Object Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/RecordActions/tests/apex/classes/recordActions/services/sflib_RecordActionsServiceImplTest.cls
/**
 * sflib_RecordActionsService test class
 *
 * This class tests the implementation of sflib_RecordActionsServiceImpl
 *
 * @see sflib_RecordActionsServiceImpl
 */
@IsTest
private class sflib_RecordActionsServiceImplTest
{
    /**
     * Tests Record Actions with two case records to see if:
     * - the first record has one action
     * - the second record has two actions in the right order
     */
    @IsTest
    static void itShouldReturnRecordActions() {
        // GIVEN two record Ids of a new case and an open case record
        final Id caseIdA = fflib_IDGenerator.generate(Case.SObjectType);
        final Id caseIdB = fflib_IDGenerator.generate(Case.SObjectType);
        final Set<Id> caseIds = new Set<Id>{caseIdA, caseIdB};

        // GIVEN three actions
        // - one for new cases
        // - two for open case records
        final sflib_RecordAction__c action1 = generateRecordAction('Action 1', Schema.Case.SObjectType, '1');
        final sflib_RecordAction__c action2 = generateRecordAction('Action 2', Schema.Case.SObjectType, '1');
        final sflib_RecordAction__c action3 = generateRecordAction('Action 3', Schema.Case.SObjectType, '1');
        action2.Order__c = 2;
        action3.Order__c = 1;

        sflib_RecordActionCondition__c condition1 = generateRecordActionCondition(1, 'Status = "New"', action1, Schema.Case.SObjectType);
        sflib_RecordActionCondition__c condition2 = generateRecordActionCondition(1, 'Status = "New"', action2, Schema.Case.SObjectType);
        sflib_RecordActionCondition__c condition3 = generateRecordActionCondition(1, 'Status = "New"', action3, Schema.Case.SObjectType);

        // WHEN we request the record actions
        System.Test.startTest();
        final Map<Id, sflib_RecordActions> results = sflib_RecordActionsService.getActions(caseIds);
        System.Test.stopTest();

        // THEN it should return two sets of actions, one set for each record
        System.Assert.areEqual(2, results.size(), 'Expected two sets, one for each record');
        System.Assert.isTrue(results.containsKey(caseIdA), 'Expected case A to be part of the result');
        System.Assert.isTrue(results.containsKey(caseIdB), 'Expected case B to be part of the result');

        // THEN case A should have one action for the new status
        System.Assert.areEqual(1, results.get(caseIdA).size(), 'Expected only one action for case A');
        System.Assert.areEqual(condition1.Id, results.get(caseIdA).getRecords().get(0).Id, 'Incorrect action assigned to case A');

        // THEN case B should have two actions for the open status
        System.Assert.areEqual(2, results.get(caseIdB).size(), 'Expected only one action for case B');
        System.Assert.areEqual(condition3.Id, results.get(caseIdB).getRecords().get(0).Id, 'Incorrect first action assigned to case B');
        System.Assert.areEqual(condition2.Id, results.get(caseIdB).getRecords().get(0).Id, 'Incorrect second action assigned to case B');
    }

    /**
     * Creates a mock sflib_RecordAction__c with the given action name and for the given record SObjectType
     *
     * @param actionName The Action Name
     * @param sObjectType The SObjectType to use
     * @param formula The condition formula
     *
     * @return Returns a sflib_RecordAction__c record mock
     */
    private static sflib_RecordAction__c generateRecordAction(String actionName, SObjectType sObjectType, String formula) {
        return new sflib_RecordAction__c(
                Id = fflib_IDGenerator.generate(sflib_RecordAction__c.SObjectType),
                FlowName__c = 'unit-test',
                Formula__c = formula,
                Name = actionName,
                Order__c = 1,
                SObjectType__c = sObjectType.getDescribe().getName(),
                Status__c = 'Active'
         );
    }

    /**
     * Creates a mock sflib_RecordActionCondition__c with the given action name and for the given record SObjectType
     *
     * @param formulaNumber The number of the condition
     * @param formula The formula to evaluate
     * @param sflibRecordAction The parent `sflib_RecordAction__c` record
     * @param sObjectType The SObjectType used for the formula evaluation
     *
     * @return Returns a sflib_RecordActionCondition__c record mock
     */
    private static sflib_RecordActionCondition__c generateRecordActionCondition(
            Decimal formulaNumber,
            String formula,
            sflib_RecordAction__c sflibRecordAction,
            SObjectType sObjectType) {
        return new sflib_RecordActionCondition__c(
                Id = fflib_IDGenerator.generate(sflib_RecordActionCondition__c.SObjectType),
                Formula__c = formula,
                Number__c = formulaNumber,
                RecordAction__c = sflibRecordAction.Id,
                SObjectType__c = sObjectType.getDescribe().getName()
        );
    }
}
 